# Site settings
title: Jekyll test
email: test@test.com
description: > # this means to ignore newlines until "baseurl:"
  Trying out Jekyll to maybe use it for another project, huzzah.
baseurl: "/jekyll-test" # the subpath of your site, e.g. /blog/
url: "http://jekylltest.com" # the base hostname & protocol for your site
twitter_username: melchoyce
github_username:  melchoyce

# Build settings
markdown: kramdown
